variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - Build

build:
  stage: Build
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker
  script: |
    find ./ -name "*.adoc" | while read i; do asciidoctor --failure-level WARN -v --trace -r asciidoctor-pdf -r asciidoctor-revealjs -a pdf-themesdir=./theming/resources/themes/ -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@4.0.2 ${i}; done
  artifacts:
    untracked: True
    expire_in: 2 weeks
