variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - Build

build:
  stage: Build
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker
  script: |
    find ./ -name "*.adoc" | while read i; do asciidoctor --failure-level WARN -v --trace --timings \
    -r asciidoctor-pdf -r asciidoctor-revealjs \
    -a pdf-themesdir=./theming/resources/themes/ \
    -a customcss=https://gitlab.com/gacybercenter/proposals-and-partnerships/-/jobs/$CI_JOB_ID/artifacts/raw/theming/resources/css/gcc_dark.css \
    -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/reveal.js ${i}; done
  artifacts:
    untracked: True
    paths:
      - ./theming/resources/css/gcc_dark.css
    expire_in: 2 weeks

