variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - Build

build:
  stage: Build
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker
  script: |
    find ./ -name "*.adoc" | while read i; do asciidoctor --failure-level WARN -v --trace --timings \
    -r asciidoctor-pdf -r asciidoctor-revealjs \
    -a pdf-themesdir=./theming/resources/themes/ \
    -a customcss=./theming/resources/reveal/css/gcc_custom.css \
    -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@3.9.2 ${i}; done
  artifacts:
    untracked: True
    paths:
      - ./theming/resources/reveal/css/gcc_custom.css
    expire_in: 2 weeks
