= 1700 Utilization Plan
:!toc:
:backend: pdf
:pdf-theme: gcc-dark

== Executive Summary

There are significant collaborative opportunities between the Georgia Cyber Center (GCC) IT team and the GCC Cyber Range team, generally focused in three areas:

. Everything-as-code
. Process Automation
. Workforce Development

Generating positive results in these three areas of interest will require adjustments to PCFs, active skill-broadening engagements, and culminate with a successful GCC refresh/upgrade into more modern and automated systems.
The IT team will adjust their PCFs to capture a need for utilization programming abilities during the course of their daily jobs.
For the A/V team, this will generally include using the Crestron (or other A/V vendor) REST API in order to configure the various devices across the campus, rather than manually touching them.
For the network and workstation team, this will include using an automated configuration management system to control networking equipment and workstations across the campus, without the need for team members to individually interact with the systems themselves.
By conducting these activities with assistance from the Cyber Range team, the IT team will be of significantly greater utility across the campus, and will be viable candidates for more difficult and better-paying occupations.

== Skill Broadening

After PCF reclassification has been completed and there are formal programming requirements across the entirety of the GCC IT staff,
the next step will be to create a career path and pipeline for technically-inclined individuals who need an entry point into the broader industry.
It will give those that are hired in to an entry level workstation or audio/visual support position exposure to and concrete experience with technologies in networking, automation, virtualization/emulation, and security research that would otherwise be significantly beyond their initial capabilities.

Formalized skill-broadening events will begin to take place in one of two categories:

. Hack-a-thon +
IT team members will be given open issues on the Georgia Cyber Range GitHub and will (via a paired programming model) propose code-based solutions to the problems for potential inclusion.
. Capture-the-Flag +
IT team members will take part in a multi-day capture-the-flag event where they solve programming challenges based around several categories (REST APIs, network programming, etc.)

Informal skill-broadening events will include:

- Access to Security Access control infrastucture, Software and Hardware
- Access to Open and Secured wired and wireless networks infrastructure
- Access to Audio Visual equipment
- Access to Desktop hardware
- Access to Network virtualization
- Access to the rural coding initiative
- Access to highly-skilled Cyber Range staff
- Access to Cyber Range interns who are probably at similar levels of programming skill and will be able to assist with onboarding

With this combined team collaboration under one roof, the professional pipeline will give individuals a pathway for professional and academic development. A person can hire in at an entry level support position, gain on the job training, take advantage of the USG TAP program to earn a degree, then furture develop there professional personna with the wide array of Information Technology avenues we have. 

== GCC Refresh

As the skills of the IT staff get broadened, the support and range staff can work collaboratively on the campus refresh plan.
This will allow the GCC to update and modernize its current systems to be as automated as possible, without necessitating the hiring of expensive external consultants.
Successful up-skilling of the IT staff will yield significant capital and operational savings, both in terms of real dollars and man hours over the course of the lifetime of the refreshed equipment.
Suite 1700 is an ideal space to develop, test, and experiment with potential replacement hardware without interfering with other business operations.

== PCF Adjustments

PCF reclassification will allow for the expansion the roles of IT by adding a programming component to each organizational role which will allow for cross-training and collaborative activities.
Additionally, broadening the skill base of each individual will allow for a deeper and more sophisticated level of support to become available to the Georgia Cyber Center without requiring expensive 3rd party training, external hires, or use of contracting for consulting services.

