= 1700 Utilization Plan
:!toc:
:backend: pdf
:pdf-theme: gcc-dark

== Executive Summary

There are significant collaborative opportunities between the Georgia Cyber Center (GCC) IT team and the GCC Cyber Range team, generally focused in three areas:

. Everything-as-code
. Process Automation
. Workforce Development

Generating positive results in these three areas of interest will require adjustments to PCFs, active skill-broadening engagements, and culminate with a successful GCC refresh/upgrade into more modern and automated systems.
The IT team will adjust their PCFs to capture a need for utilization programming abilities during the course of their daily jobs.
For the A/V team, this will generally include using the Crestron (or other A/V vendor) REST API in order to configure the various devices across the campus, rather than manually touching them.
For the network and workstation team, this will include using an automated configuration management system to control networking equipment and workstations across the campus, without the need for team members to individually interact with the systems themselves.
By conducting these activities with assistance from the Cyber Range team, the IT team will be of significantly greater utility across the campus, and will be viable candidates for more difficult and better-paying occupations.

== PCF Adjustments
The Goal of the PCF reclassification is to expand the rolls of IT by adding a programming component, cross training component and adding a deeper level of support that broading the skill base of each individual. 

== Skill Broadening
The goal here is to create a career path and pipeline for IT minded individuals who need an entry point into the industry. It will give those that can come in at an entry level workstation or Audio Visual support postion and give them access and added training in networking, virtualization(cyber range), automation and a whole host of cyber security experience. 

== GCC Refresh
The support and range staff can work collaboratively to automate the campus refresh. the goal is to have a space the will have a physical bench style environment that will allow technicians and developers to build, test, teardown and deploy from a central location outside of the public eye. 

== 
