= Coding for Rural Georgians - FY22 Expansion
:!toc:
:backend: pdf
:pdf-theme: gcc-blue

== Executive Summary

For the original program overview and goals, go https://gitlab.com/gacybercenter/proposals-and-partnerships/-/jobs/artifacts/master/raw/proposals/rural-coding.pdf?job=build[here].

== Program Expansion Goals

* 20x increase in supported student count (up to 3240)
* Addition of 'advanced' and 'expert' modules with different contract price points ($15k max, $25k max)
* Explicitly tie every curriculum module to one or more requirements from https://www.georgiastandards.org/[Georgia Standards]
* Formalize advertising/outreach campaigns for content creator pipeline
* Add support for physical hardware integration (e.g. raspberry pi, software defined radios, etc.)

== FY 2022 Budget Request

.Projected Capital Costs for Program Expansion (one-time)
[cols="1,1", options="header,footer"]
|===
|Item |Cost
|Software Engineering |$200,000
|Development Hosting |$50,000
|Content Creation |$400,000
|Miscellaneous (Advertising, Content Creator program on-boarding materials, etc.) |$100,000
|*Total Capital Cost* |*$750,000*
|===

.Projected Operational Costs for Program Expansion (annual recurring)
[cols="1,1", options="header,footer"]
|===
|Item |Cost
|20% Makerspace Technician FTE (fringe incl.) |$20,000
|50% Courseware-as-Code Content Creator FTE (fringe incl.) |$75,000
|20% Hardware lifecycle | $100,000
|*Total Annual Recurring Cost* |*$195,000*
|===

*Total FY 2022 Ask: $945,000*

== FY 2022 Budget Breakdown and spend plan

This section breaks down each budgetary line item and outlines more detail about how it will be spent.

=== Software Engineering

This line item focuses on updating and maintaining the framework to support additional requirements from the advanced and expert modules, mostly centered around adding support for external hardware and more complicated practical exercises.
For more information about rates, go https://gitlab.com/gacybercenter/proposals-and-partnerships/-/jobs/artifacts/master/raw/proposals/rural-coding.pdf?job=build[here].

=== Development Hosting

This section accounts for providing a development and test environment for the software engineering work.

=== Content Creation

This line item is dedicated to content creation; the backbone of the entire program.
Following on the initial 5 'basic' modules developed with AFY21 funding, the larger FY22 program will allocate content development assets in the following manner:

.Content Budget
[cols="1,1,1", options="header"]
|===
|Item |Quantity |Cost
|Basic Modules |~22 |$225,000
|Advanced Modules |~5 |$125,000
|Expert Modules |~2 |$50,000
|===

For information on how content creation contracts will be issued, go https://gitlab.com/gacybercenter/proposals-and-partnerships/-/jobs/artifacts/master/raw/proposals/rural-coding.pdf?job=build[here].

=== Miscellaneous

This line item accounts for miscellaneous expenses associated with growing the program.
This includes (but is not limited to) advertising, creation of onboard documentation, creation of procurement process navigation documentation (for laypeople), administrative overhead (mostly related to contract management), user guides, developer guides, and more.

=== Makerspace Technician FTE (20%)

This line item pays for 20% of a full time employee (approximately 400 hours/year).
The purpose of this employee is to design, test, and validate hardware required for any of the advanced or expert modules.
Additionally, they may participate in (unpaid beyond actual salary) content creation activities when the course material aligns with their skill set.

=== Courseware-as-Code Content Creator FTE (50%)

This line item pays for 50% of a full time employee (approximately 1000 hours/year).
The purpose of this employee is to manage content creation activities (e.g. perform QA/QC on contracted content to ensure that it meets the requirements of the State) and create content where no viable contract proposal can be found.
This individual will work closely with the Makerspace Technician, although there will be no supervisory relationship between them.

=== Hardware Lifecycle (20%)

This line item pays for the maintenance of the hardware that powers the system by providing partial lifecycle funding as an operational expense rather than a capital one.
