= Coding for Rural Georgians
:!toc:
:backend: pdf
:pdf-theme: gcc-blue

== Executive Summary

Georgia has the third largest population of rural students in the USA after Texas and North Carolina.
Providing technical skills and education is a challenge in rural Georgia counties such as Taliaferro, Hancock, and Toombs.
This is often due to lack of experienced teachers, technical equipment, and sufficient after-school support systems.
Given the economic disadvantages typically experienced by rural counties, these are not problems that are easily solved.
Due to these challenges, rural students are placed at a significant disadvantage when entering the workforce through no fault of their own.

The Georgia Cyber Center seeks to address these inequalities by pioneering the online and offline delivery of foundational computer science, electrical engineering, and mathematical education without the need for significant capital investment or additional hiring actions in these underserved areas.
Recently, the Georgia Cyber Center  met with Taliaferro County's superintendent to discuss a pilot program that would begin to redress these issues.

The goal is to bring an engaging and interactive curriculum to students and connect them with the best teaching talent from across the nation regardless of zip code while allowing highly talented and qualified teachers to reside wherever they choose.

== Framework

The first major item that must be addressed is determining the framework in which the curriculum shall reside.
There are two key requirements:

. The framework must have an open source license
. The framework must be able to be run in areas that have poor or no connectivity and provide an *identical* experience to those who do have internet access

By ensuring that these requirements are met, we can be certain that the project is not subject to vendor lock-in and that individuals who do not have internet access (who are overwhelmingly rural) are able to reap the benefits.

=== Requirements

Effective computer science and electrical engineering education must include a hands-on component that allows students to practice skills and techniques learned in the curriculum.
Any framework that supports this kind of education must be able to ingest lesson content from various different educators in the form of text, pictures, video, and more.
Building a fully-featured greenfield project that will capture these requirements AND provide the flexibility required to adapt to new technologies and trends would be an enormously expensive undertaking.

In order to maximize the return on the investment, an optimal solution will build upon an already-existing product in a collaborative manner.
Solving the problem in this manner will ensure that there is no cost duplication and that the vast majority of the expenditure will go towards solving the problem at hand rather than administrative overhead.
Additionally, working on the framework in a collaborative and open manner will encourage others to contribute, further increasing the return for the Georgia taxpayer.

The framework will be modified to have the following features:

* Automatic, one-click set up of student curriculum for the chosen lesson(s)
* Support for graphical interfaces rather than just command line interfaces
* Full support for local deployment of the framework for students who do not have reliable internet access

The framework provides a layer of abstraction by enabling users to interact with hands-on environments that are provisioned on-demand and presented interactively in the browser in an intuitive, graphical interface.
It also allows for students to work on their coding abilities outside of the classroom - all relevant lessons will have a required accompanying video instructor component from a top-tier computer science teacher, with links to additional resources if necessary.
The goal of the framework would be to provide a turn-key solution that allows students and/or faculty to focus on the technical concept being taught instead of troubleshooting and configuration of a complex learning environment.

=== Cost Estimate

The cost for modifying the framework is generally restricted to software engineering costs along with the accompanying infrastructure costs related to the activities of developing, building, and testing the framework.

* Software Engineer Deliverables:
** Fix known and relevant bugs in framework prior to starting new work
** Locally develop required framework modifications
*** Hands-on activities with graphical interface support
*** "Internet Desert" support
*** Video lesson support
** Integrate locally developed modifications with upstream maintainers

.Estimated Costs
[cols="1,2,2", options="header"]
|===
|Costs |Estimated Hourly Rate |Estimated Potential Cost
|Software Engineer |640 hours @ ~$120/hour |$76,800
|Development Hosting |N/A |$10,000
|===

== Content

The best educational framework in the world is useless without engaging, relevant, and accurate educational content.
As one of the main barriers to successful computer science and electrical engineering education in rural Georgia is a lack of qualified teachers in these areas, the Georgia Cyber Center seeks to bridge that divide by allowing the teachers to educate students from anywhere in the nation.

=== Lessons Development
The Georgia Cyber Center proposes that fixed-price contracts at a rate of $5,000 per 80-hour module will be offered on the open-market.
Offerors will be able to submit responses to the various Requests for Proposal, and the Georgia Cyber Center will award to the best suited candidate (or none if there is no acceptable proposal).
As the labyrinthine state procurement process will be daunting for the uninitiated (and particularly since we are actively trying to avoid the same tired and incumbent solutions), the Georgia Cyber Center will take great care in making step-by-step procurement process materials for distribution specifically for our target audience of computer scientists.
Using this innovative procurement strategy, the Georgia Cyber Center will ensure that rural Georgians will have access to the best-qualified educators from around the country.

All lessons will include:

* Video recordings of the instructor going over the lesson
* Written student guides (akin to a traditional textbook in function, but not form)
** Custom made instructional materials with step-by-step practical exercise instructions available if students get stuck
** Links to other well known and reputable resources
* Practical exercises

All content will be created using the courseware-as-code paradigm.
All learning materials, practical exercises, and virtual environments are to be stored as simple text in a Git repository.
This allows for rapid modification and addition to content, significantly decreasing upkeep costs of the materials over time.
Instructions on how to successfully create these kinds of materials will be created by the GCC for easy distribution.

All work will be open-source and published on the internet, further cementing the reputations of Georgia Cyber Center, Augusta University, and Georgia as technology and innovation leaders.

The initial tranche of course content will consist of the following modules:

* General Debugging +
_Strategies and techniques for analyzing code for bug identification and resolution_
* Introductory GO +
_Introduction to the open-source general-purpose programming language created at Google._
* Introductory Rust +
_Introduction to the open-source static multi-paradigm programming language that is focused on security and performance._
* Arduino Programming +
_Programming using an open-source electronics prototyping microcontroller platform built around an easy-to-understand programming language._
* Discrete Mathematics +
_Study of mathematical structures that are non continuous, distinct, and separable.
This area of mathematics is especially applicable to coding and software engineering and is a critical component for any successful developer_

=== Cost Estimate

.Curriculum Development
[cols="1,1", options="header"]
|===
|Costs |Estimated Cost Per Module
|Curriculum Developer/Educator |$5,000
|===

* Curriculum Developer/Educator Deliverables:
** Video Recordings
** Written Student Guides
** Practical Exercises/Labs

== Future Work

This initial phase of the project can be just the beginning.
The framework can be expanded beyond just technical topics to include anything taught in the classroom: history, mathematics, english, and more.
The value of being able to deliver top-tier, vetted educators directly into the homes of our rural students is undeniable.

In addition to adding new types of course content, the framework can also be expanded to track student progress over time, introduce gamification into the lessons, integrate with in-school learning management systems, and much more.

Costs per lesson would stay static at $5,000 per 80 hours of content (notwithstanding changes in labor rates, inflation, or other unforeseen events).
Maintenance costs related to the framework would increase as features were added, although at a significantly lower rate than if it was a closed-source product.
Hosting costs for production deployments of the framework would vary widely depending on the size and complexity of the deployment, but would be insignificant (5% total cost or less) in relation to the capital outlays associated with framework development and content creation.

== Conclusion
Addressing the problem in this manner allows Georgia Cyber Center the ability to provide additional materials for students to use inside and outside the classroom, while also encouraging the best teachers from across the nations to contribute content that can be used by anyone at a nominal cost.
