= Coding for Rural Georgians
:!toc:
:backend: pdf
:pdf-theme: gcc-blue

== Executive Summary

Georgia has the third largest population of rural students in the USA after Texas and North Carolina.
Providing technical skills and education is a challenge in rural Georgia counties such as Taliaferro, Hancock, and Toombs.
This is often due to lack of experienced teachers, technical equipment, and sufficient after-school support systems.
Given the economic disadvantages typically experienced by rural counties, these are not problems that are easily solved.
Due to these challenges, rural students are placed at a significant disadvantage when entering the workforce through no fault of their own.

The Georgia Cyber Center seeks to address these inequalities by pioneering the online and offline delivery of foundational computer science, electrical engineering, and mathematical education without the need for significant capital investment or additional hiring actions in these underserved areas.
Recently, the Georgia Cyber Center  met with Taliaferro County's superintendent to discuss a pilot program that would begin to redress these issues.

The goal is to bring an engaging and interactive curriculum to students and connect them with the best teaching talent from across the nation regardless of zip code while allowing highly talented and qualified teachers to reside wherever they choose.

== Framework

The first major item that must be addressed is determining the framework in which the curriculum shall reside.
There are two key requirements:

. The framework must have an open source license
. The framework must be able to be run in areas that have poor or no connectivity and provide an *identical* experience to those who do have internet access

By ensuring that these requirements are met, we can be certain that the project is not subject to vendor lock-in and that individuals who do not have internet access (who are overwhelmingly rural) are able to reap the benefits.

=== Requirements

Effective computer science and electrical engineering education must include a hands-on component that allows students to practice skills and techniques learned in the curriculum.
Any framework that supports this kind of education must be able to ingest lesson content from various different educators in the form of text, pictures, video, and more.
Building a fully-featured greenfield project that will capture these requirements AND provide the flexibility required to adapt to new technologies and trends would be an enormously expensive undertaking.

In order to maximize the return on the investment, an optimal solution will build upon an already-existing product in a collaborative manner.
Solving the problem in this manner will ensure that there is no cost duplication and that the vast majority of the expenditure will go towards solving the problem at hand rather than administrative overhead.
Additionally, working on the framework in a collaborative and open manner will encourage others to contribute, further increasing the return for the Georgia taxpayer.

The framework will be modified to have the following features:

* Automatic, one-click set up of student curriculum for the chosen lesson(s)
* Support for graphical interfaces rather than just command line interfaces
* Full support for local deployment of the framework for students who do not have reliable internet access

The framework provides a layer of abstraction by enabling users to interact with hands-on environments that are provisioned on-demand and presented interactively in the browser in an intuitive, graphical interface.
It also allows for students to work on their coding abilities outside of the classroom - all relevant lessons will have a required accompanying video instructor component from a top-tier computer science teacher, with links to additional resources if necessary.
The goal of the framework would be to provide a turn-key solution that allows students and/or faculty to focus on the technical concept being taught instead of troubleshooting and configuration of a complex learning environment.

=== Cost Estimate


* Software Engineer Deliverables:
** Modification of open source framework
** Integration and hosting configuration

.Software Engineer
[cols="1,1,2", options="header"]
|===
|Costs
|Maximum Billable Total
|Total Potential Cost

|Software/Automation Engineer
|320 hours @ ~$200/hr
|$64,000

|===

.Hosting Costs
[cols="1,1,2", options="header"]
|===
|Costs
|Maximum Billable Total
|Total Potential Cost

|Hosting (AWS/Azure)
| hours @ ~/hr
|$

|===

== Content

=== Lessons/Content Development
GCC will offer 'bounties' for individuals to create high-quality course content per specified module. This will be accomplished through contracting of top educators around the nation to contribute through video recording and individual lesson creation.

Lessons will include:

* Video recordings of the instructor going over the lesson

* Written student guides, which will include custom made instructional materials, as well as links to other, will known/reputable resources

* Practical exercises, with automatic grading

* An option for tracking progress over time

All content will be created using the courseware-as-code concept, all learning materials, practical exercises, and virtual environments are stored as simple text/code in a Git repository. This allows for rapid modification and addition to content.

All work will be open-source and published on the internet, further cementing the reputations of GCC, AU, and GA as technology and innovation leaders.

Course content will include the following modules:

* General Debugging +
_Strategies and techniques for analyzing code for bug identification and implemention of real-world solutions_
* Introductory GO +
_Introduction to the open-source general-purpose programming language created at Google._
* Introductory Rust +
_Introduction to the open-source static multi-paradigm programming language that is focused on security and performance._
* Arduino Programming +
_Programming using an open-source electronics prototyping microcontroller platform built around an easy to understand programming language._
* Discrete Math +
_Study of mathematical structures that are non continuous, distinct, and seperable_

=== Cost Assessment Per Module

.Curriculum Development
[cols="1,1", options="header"]
|===
|Costs
|Total Potential Cost (per module)

|Curriculum Developer/Consultant
|$5,000

|===

* Curriculum Developer Deliverables:
** Video Recordings
** Written Student Guides
** Written Instructor Guides
** Practical Assessments / Labs

=== Conclusion
Addressing the problem in this manner allows GCC the ability to provide additional materials for students to use inside and outside the classroom, while also encouraging the best teachers from across the nations to contribute content that can be used by anyone at a reasonable cost.
