= Taliaferro Virtual Education Proposal
:!toc:
:backend: pdf
:pdf-theme: gcc-blue

== Executive Summary
Proividing technical skills and education is a challenge in rural GA counties such as Taliaferro County. This is often due to lack of technical, educational, and personnel resources. Due to these challenges, students are often placed at a disadvantage compared to those from more populated communities.

The Georgia Cyber Center seeks to remove the barriers to technical resources by offering technical virtual education and training. Recently, GCC has met with Taliaferro County's superintendent to discuss providing technical training without burdening current faculty.

The goal is to bring an engaging and interactive curriculum to students and connect them with the best teaching talent from across the nation regardless of zip code.

== Short Term
=== Open Source Framework
Technical training must encompass a hands-on component that allows students to perform actions learned in the curriculum. To that end, GCC will explore modification of an open-source framework. The framework is originally designed for training network engineers on advanced infrastructure topics such as automation. This will be adapted to lessons and content that are developed as part of the curriculum.

The open-source framework will be designed and modified to overcome the following typical technical training issues:

* Infrastructure setup
* Training environment configuration for students and instructors

The open-source framework provides a level of abstraction by enabling users to interact with real virtual environments that are provisioned on-demand and presented interactively in the browser in an intuitive gui driven interface. Modifications will be made for an off-line option due to internet bandwidth restrictions for a 100% identical experience.

The goal of the open-source framework would be to provide a turn-key solution that allows students and faculty to focus on the technical concept being taught instead of troubleshooting and configuration of a complex learning environment.

=== Cost Assessment
* Software Engineer Deliverables:
** Modification of open source framework
** Integration and hosting configuration

.Software Engineer
[cols="1,1,2", options="header"] 
|===
|Costs
|Maximum Billable Total
|Total Potential Cost

|Software/Automation Engineer
|320 hours @ ~$200/hr
|$64,000

|===

.Hosting Costs
[cols="1,1,2", options="header"] 
|===
|Costs
|Maximum Billable Total
|Total Potential Cost

|Hosting (AWS/Azure)
| hours @ ~/hr
|$

|===

== Long

=== Lessons/Content Development
Once the framework has been modified, the GCC will offer 'bounties' for individuals to create high-quality lessons of the kind needed for usage with the modified framework. This will be accomplished through contracting of top educators around the nation to contribute through video recording and individual lesson creation.

Lessons will include:

* Video recordings of the instructor going over the lesson

* Written student guides, which will include custom made instructional materials, as well as links to other, will known/reputable resources

* Practical exercises, with automatic grading

* An option for tracking progress over time

All content will be created using the courseware-as-code concept, all learning materials, practical exercises, and virtual environments are stored as simple text/code in a Git repository. This allows for rapid modification and addition to content.

All work will be open-source and published on the internet, further cementing the reputations of GCC, AU, and GA as technology and innovation leaders.

Content will include the following:

* General Debugging +
_Strategies and techniques for analyzing code for bug identification and implemention of real-world solutions_
* Introductory GO +
_Introduction to the open-source general-purpose programming language created at Google._
* Introductory Rust +
_Introduction to the open-source static multi-paradigm programming language that is focused on security and performance._
* Arduino Programming +
_Prgoramming using an open-source electronics prototyping microcontroller platform built around an easy to understand programming language._
* Discrete Math +
__

=== Cost Assessment Per Module
* Curriculum Developer Deliverables:
** Video Recordings
** Written Student Guides
** Written Instructor Guides
** Practical Assessments / Labs

.Curriculum Development
|===
|Costs|Total Potential Cost
|Curriculum Developer/Consultant|$5,000
|===

=== Conclusion
By tackling this problem in this manner, the GCC can create additional materials for students to use inside and outside the classroom, while also encouraging the best teachers from across the nation to create content that can be used by anyone.
