= Internship Opportunities at the Georgia Cyber Range
Chris Apsey <capsey@augusta.edu>
:!toc:
:pdf-theme: gcc-blue

include::../templates/gcr_intro.adoc[]

== Computer Science

There are numerous paid opportunities for Computer Science students, mostly focused in the area of computer programming.
Some of the languages/frameworks/DSLs used in the Georgia Cyber Range include:

* python
* salt/jinja
* C
* javascript/css/html

Students should have functional knowledge in one or more of these areas, as they will be actively contributing to the upstream, open-source projects that power the Georgia Cyber Range and their contributions will become a permanent fixture in the respective project(s).
Once the work of the students has been accepted into upstream, the Georgia Cyber Range will pull down the improvements and they will become an official part of the suite of capabilities offered by the Georgia Cyber Range.

In addition to traditional programming opportunities, there are opportunities for working on distributed systems optimization, specifically relating to the usage and implementation of algorithms such as Paxos, RAFT, CRUSH, and others.

There are also software defined networking opportunities (such as pushing a layer 3 topology all the way to the host as an underlay network) available as well.

== Cybersecurity Engineering/Electrical Engineering

The Georgia Cyber Center was awarded a grant from the Army Cyber Institute focused on improving the tooling that is available to security researchers interested in critical infrastructure.
The Georgia Cyber Center plans to invest directly in improving the quality and utility of freely available software that is useful when working on critical infrastructure security.
These investments in open-source projects will immediately be re-incorporated into the Georgia Cyber Range, giving it an even greater set of unique capabilities directly focused on enabling research against critical infrastructure components,
specifically in the realm of natively supporting the alternative architectures and proprietary protocols/hardware that the systems rely on, giving security researchers a highly productive, low-risk environment in which to ply their trade.

These efforts directly link to the cybersecurity engineering and electrical engineering disciplines by providing opportunities to perform operational technology/industrial control/SCADA integrations with the Georgia Cyber Range for the explicit purpose of conducting security research.
