= Georgia Cyber Summit 2020
Chris Apsey <capsey@augusta.edu>
:backend: revealjs
:imagesdir: https://gitlab.com/gacybercenter/theming/-/raw/master/resources/images/
:title-slide-background-image: gcc_grey_title_bg.svg
:revealjs_theme: black

== What is a Cyber Range?

[%step]
* Turing Machine

.Characteristics
* Reproducibility
* Observability
* Unique capabilities at scale

[.notes]
--
* At this point, a 'Cyber Range' is anything that can process binary data.
It has lost all meaning in the modern technical lexicon, mostly due to unscrupulous marketing of rebranded,
already-existing products that don't offer any real additional functionality.

* If you went out and bought a commercial 'cyber range' offering, you probably bought something that you already had.

* 3 key differentiators for what a 'cyber range' should be:
** Reproducibility - Every 'experiment' should be able to be independently reproduced by anyone, anywhere
** Observability - Every 'experiment' should be able to be able to be transparently examined from start to finish
** Unique capabilities at scale - A Cyber Range should offer significant capabilities beyond what is available in traditional IT systems at scale
--

image::gcc_black_bg.svg[background, size=100%]

== A Brief History of the GCR

[%step]
* Army
* Open-Source
* GCC Stewardship

[.notes]
--
notes here
--

image::gcc_black_bg.svg[background, size=100%]

=== History Subslide

* Stuff

image::gcc_black_bg.svg[background, size=100%]

== Why we are different

* Embedded Systems
* Not replicating things that everyone else already does

[.notes]
--
notes here
--

image::gcc_black_bg.svg[background, size=100%]

== Current Efforts

* ACI Grant
* Some other thing

[.notes]
--
notes here
--

image::gcc_black_bg.svg[background, size=100%]

== The Future

* Rural Efforts
* Other things

[.notes]
--
notes here
--

image::gcc_black_bg.svg[background, size=100%]
