= Operational Technology and OpenStack, a love story
Chris Apsey <capsey@augusta.edu>
:backend: revealjs
:imagesdir: https://gitlab.com/gacybercenter/theming/-/raw/master/resources/images/
:title-slide-background-image: gcc_grey_title_bg.svg
:revealjs_theme: black

== What is Operational Technology?
image::gcc_black_bg.svg[background, size=100%]

[%step]
* Planes
* Trains
* Automobiles

[.notes]
--
* GA-specific
** Hartsfield-Jackson - Busiest airport in the world
** Port of Savannah - 3d Busiest seaport in the US

All of these things are powered by computers, generally with non-x86 architectures.
ARM is around, but MIPS, SPARC, POWER, blackfin, and other undocumented ones are plentiful.
--

== Why should I care?
image::https://www.verywellmind.com/thmb/rg799yWpY5SYaJzxUbJtE9P9U54=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4136760-article-what-is-maslows-hierarchy-of-needs-5a97179aeb97de003668392e.png[background, size=100%]

[.notes]
--
* Abraham Maslow said so
** Food, water, warmth, rest
** Security, safety

One of the great ironies in systems security is the fact that the most critical components that make day-to-day life possible across the world are also some of the most poorly designed and defended.

This is due to a myriad of reasons, but can generally be boiled down to:

* Vendors must provide functionality first to stay in business and security comes as an afterthought, if considered at all
* Manufacturers and developers do not invest time in trying to understand what new tools, techniques, and research results are available that can contribute to the security posture of their systems
* Lack of available technical personnel with required skillsets, exacerbated by an incredibly high barrier to entry for new personnel looking to become experts in this space
* Unwillingness of vendors and manufacturers to provide systems insight due to fear of bad publicity
* General lack of urgency due to incorrect perception that high-profile 'hacks' (Sony, Atlanta, Equifax) that drive news cycles are more deserving of attention than critical infrastructure issues

The reality is that while the 'hacks' that can be read about in the news are unfortunate, they are generally fiscal inconveniences for the affected rather than life-or-death events.
--

== What can we do about it?
image::gcc_black_bg.svg[background, size=100%]

[%step]
* Make it easier for researchers to investigate these types of systems
** Improve multi-arch support in OpenStack (to include pure emulation)
** Add support for other protocols to neutron (e.g. modbus)
** Write cyborg drivers
* Encourage manufacturers to be more open
* Connect researchers to manufacturers

[.notes]
--
A common feature of modern technical systems is internet connectivity.
This connectivity has its pros and cons from a security perspective,
but one of the most significant advantages is the ability for that system to be assessed under the guise of a formal bug bounty program.

These bug bounty programs invite the general public to ethically assess and test systems for potential security holes,
and then responsibly disclose them to the system owner in exchange for compensation.
This mechanism yields significant financial, public relations, and product resiliency advantages to the participants at nominal relative cost.

The industrial control systems that power water and gas distribution, electric generation, airports, seaports, traffic control systems, dam controls, and other critical infrastructure are generally not connected to the internet, and thus cannot partake in such programs.
This Georgia Cyber Center seeks to bridge that gap and allow manufacturers, municipalities, and the general public to reap then benefits of more secure and resilient infrastructure.
--

== Current Efforts
image::gcc_black_bg.svg[background, size=100%]

[%step]
* Army Cyber Institute Grant
* Bug bounty program

[.notes]
--
ACI grant feature to be included in Wallaby (fingers crossed)
Bug bounty program to be operational in CY21
--

== Future Efforts
image::gcc_black_bg.svg[background, size=100%]

[%step]
* Published curriculum focused on getting people in to OT security research
* More contributions to OpenStack...
* We're hiring! <capsey@augusta.edu>

[.notes]
--
--
